#!/usr/bin/env python3
"""Generate src/moli/nfc_tables.odin from the Unicode Character Database.

Inputs (gitignored under dict/ucd/, from Unicode 17.0.0 at
https://www.unicode.org/Public/17.0.0/ucd/):
  UnicodeData.txt               - canonical combining classes + canonical
                                  decomposition mappings
  DerivedNormalizationProps.txt - Full_Composition_Exclusion (composites
                                  that must not be re-composed)

Outputs flat constant i32 arrays (scalar constant data, indexed
through materialized locals - variable indexing into constant data is
a compile error): pairs for combining classes, triples for
canonical decompositions (b = -1 marks a singleton), triples for
primary composites sorted by (a, b). Hangul is algorithmic at runtime
and absent from the tables.

Usage: python3 scripts/gen_nfc_tables.py   (from the repo root)
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UCD = ROOT / "dict" / "ucd"
OUT = ROOT / "src" / "moli" / "nfc_tables.odin"


def main() -> None:
    ucd_lines = (UCD / "UnicodeData.txt").read_text().splitlines()
    dnp_lines = (UCD / "DerivedNormalizationProps.txt").read_text().splitlines()

    version = re.search(r"DerivedNormalizationProps-(\S+?)\.txt",
                        dnp_lines[0]).group(1)

    ccc: dict[int, int] = {}
    decomp: dict[int, tuple[int, ...]] = {}
    for line in ucd_lines:
        f = line.split(";")
        cp = int(f[0], 16)
        c = int(f[3])
        if c != 0:
            ccc[cp] = c
        d = f[5].strip()
        if d and not d.startswith("<"):
            decomp[cp] = tuple(int(x, 16) for x in d.split())

    excluded: set[int] = set()
    for line in dnp_lines:
        m = re.match(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*Full_Composition_Exclusion", line)
        if m:
            lo = int(m.group(1), 16)
            hi = int(m.group(2), 16) if m.group(2) else lo
            excluded.update(range(lo, hi + 1))

    compose: dict[tuple[int, int], int] = {}
    for cp, d in sorted(decomp.items()):
        if len(d) != 2:  # only pairs compose; singletons never do
            continue
        if cp in excluded:
            continue
        if 0xAC00 <= cp <= 0xD7A3 or 0x1100 <= cp <= 0x11FF:
            continue  # Hangul is algorithmic
        a, b = d
        compose[(a, b)] = cp

    def fmt_array(name: str, vals: list[int], comment: str) -> str:
        body = []
        for i in range(0, len(vals), 12):
            body.append("\t" + " ".join(f"{v}," for v in vals[i:i + 12]))
        return f"// {comment}\n{name} :: [?]i32{{\n" + "\n".join(body) + "\n}\n"

    parts = [
        "// Code generated by scripts/gen_nfc_tables.py from the Unicode",
        f"// Character Database {version}: UnicodeData.txt (canonical combining",
        "// classes and canonical decompositions) plus DerivedNormalizationProps.txt",
        "// (Full_Composition_Exclusion). The UCD is distributed under the Unicode",
        f"// License; regenerating needs the two files under dict/ucd/. Do not edit.",
        "//",
        "// Flat i32 arrays on purpose (scalar constant data, indexed through",
        "// materialized locals — variable indexing into constant data is a",
        "// compile error). Layouts:",
        "//   NFC_CCC     pairs   (rune, combining class)        - sorted by rune",
        "//   NFC_DECOMP  triples (from, a, b; b -1 = singleton) - sorted by from",
        "//   NFC_COMPOSE triples (a, b, composed)              - sorted by (a, b)",
        "// Hangul composition/decomposition is algorithmic and absent here.",
        "package moli",
        "",
    ]

    ccc_vals: list[int] = []
    for cp in sorted(ccc):
        ccc_vals += [cp, ccc[cp]]
    parts.append(fmt_array("NFC_CCC", ccc_vals,
                           "Canonical combining classes (0 = starter omitted)."))

    dec_vals: list[int] = []
    for cp in sorted(decomp):
        d = decomp[cp]
        dec_vals += [cp, d[0], d[1] if len(d) == 2 else -1]
    parts.append(fmt_array("NFC_DECOMP", dec_vals,
                           "Canonical decomposition mappings (Hangul omitted)."))

    com_vals: list[int] = []
    for (a, b) in sorted(compose):
        com_vals += [a, b, compose[(a, b)]]
    parts.append(fmt_array("NFC_COMPOSE", com_vals,
                           "Primary composites (a, b) -> composed; exclusions and Hangul omitted."))

    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT}: {len(ccc)} ccc, {len(decomp)} decomp, {len(compose)} compose")


if __name__ == "__main__":
    sys.exit(main())
