#!/usr/bin/env python3
"""Generate src/moli/lemma_zh_ts.odin from the OpenCC TSCharacters
mapping (traditional -> simplified single characters, first candidate).

Input (gitignored under dict/ucd/): TSCharacters.txt from
https://github.com/BYVoid/OpenCC (Apache-2.0). Identity mappings are
dropped. Output is one flat i32 array (pairs, sorted by traditional
codepoint) - flat on purpose (scalar constant data, indexed through
materialized locals; variable indexing into constant data is a
compile error).

Usage: python3 scripts/gen_lemma_tables.py   (from the repo root)
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "dict" / "ucd" / "TSCharacters.txt"
OUT = ROOT / "src" / "moli" / "lemma_zh_ts.odin"

def main() -> None:
    pairs = []
    for line in SRC.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        trad, values = parts[0], parts[1].split()
        if not values:
            continue
        simp = values[0]
        if simp == trad:
            continue
        pairs.append((ord(trad), ord(simp)))
    pairs.sort()
    body = []
    vals = [v for p in pairs for v in p]
    for i in range(0, len(vals), 12):
        body.append("\t" + " ".join(f"{v}," for v in vals[i:i + 12]))
    text = "\n".join([
        "// Code generated by scripts/gen_lemma_tables.py from the OpenCC",
        "// TSCharacters.txt mapping (traditional -> simplified, first",
        "// candidate; identities dropped). OpenCC is Apache-2.0",
        "// (github.com/BYVoid/OpenCC); regenerating needs the file under",
        "// dict/ucd/. Do not edit. Character-level only - phrase-level",
        "// conversions need the full OpenCC phrase dictionaries.",
        "//",
        "// Flat i32 pairs (traditional, simplified), sorted by traditional.",
        "package moli",
        "",
        f"ZH_TS_CHARACTERS :: [?]i32{{",
        *body,
        "}",
        "",
    ])
    OUT.write_text(text)
    print(f"wrote {OUT}: {len(pairs)} character mappings")

if __name__ == "__main__":
    main()
